extends Object

class_name ScriptWriter

const generated_warning = """###WARNING. This file is automatically generated and is not supposed to be edited manually.
###If you need to define custom functions for this resource, use the script in the 'Game/Models' directory instead."""

func write_script(path : String, name : String, extend : String, lines := PoolStringArray([]), custom = false, classname = null):
	find_or_create_directory(path)
	var file := File.new()
	file.open(path+name,File.WRITE)
	if extend.split(".")[-1] == "gd":
		file.store_line('extends "'+extend+'"\n')
	else:
		file.store_line('extends '+extend+'\n')
	if classname:
		file.store_line("class_name "+classname+"\n")
	if !custom:
		file.store_line(generated_warning)
	for line in lines:
		file.store_line(line)
	file.close()
	
func find_or_create_directory(path:String):
	var dir := Directory.new()
	if !dir.dir_exists(path):
		dir.make_dir_recursive(path)
		dir.open(path)

func build_setget_function(variable_name:String, prefix:="set_"):
	# to be used for establishing relation to other (singleton) resources
	# possibly divide into two functions
	var body := PoolStringArray([])
	var head = "func "+prefix+variable_name
	if prefix == "set_":
		head+="(value):"
	else:
		head+="()"
	body.push_back("func "+prefix+variable_name)
	
	return body.join("\n")
