extends "res://CM/Resources/ActiveRecord.gd"

###WARNING. This file is automatically generated and is not supposed to be edited manually.
###If you need to define custom functions for this resource, use the script in the 'Game/Models' directory instead.
### A singleton for different location types to navigate.
export var name : String setget set_name
const icon_path = "res://Game/Graphics/LocationType/icon/{name}.png"
export (Texture) var icon setget set_icon, get_icon
const display_name_key = "LocationType__{item_name}__display_name"
export var display_name : String setget set_display_name, get_display_name

func _to_string():
	return "[LocationType:{name}]".format({"name" : get("name")})
	

func instance_as(context_name : String, secondary_contexts = {}):
	var context_scene = load(Content.scenes_path + "LocationType/" + context_name + ".tscn")
	if !context_scene:
		return .instance_as(context_name, secondary_contexts)
	var instance = context_scene.instance()
	instance.set("location_type", self)
	for secondary_context in secondary_contexts:
		instance.set(secondary_context, secondary_contexts[secondary_context])
	return instance
	
func set_name(value):
	name = value
	emit_changed()

func get_icon():
	icon = load(icon_path.format({"name": name}))
	if !icon:
		icon = load(icon_path.format({"name": "placeholder"}))
	return icon

func set_icon(value):
	icon = value
	emit_changed()

func get_display_name():
	return display_name_key.format({"item_name" : name})
	
		
func set_display_name(value):
	display_name = value
	emit_changed()

func get_locations(additional_filters := {}):
	var filter = {"location_type" : self}
	for key in additional_filters:
		filter[key] = additional_filters[key]
	return Content.get_all_filtered("Location",filter)

