extends "res://CM/Resources/ActiveRecord.gd"

###WARNING. This file is automatically generated and is not supposed to be edited manually.
###If you need to define custom functions for this resource, use the script in the 'Game/Models' directory instead.
### Location class.
###
###Level = as the map goes in certain direction, the level multiplied by it is the location's base position.
###
###Position - position on map
export var name : String setget set_name
export var location_type : Resource setget set_location_type
export var position : Vector2 setget set_position
export var level := 0 setget set_level
export var starting := false setget set_starting
export var current := false setget set_current
export var visited := false setget set_visited
export var actual_position : Vector2 setget set_actual_position

func _to_string():
	return "[Location:{name}]".format({"name" : get("name")})
	

func instance_as(context_name : String, secondary_contexts = {}):
	var context_scene = load(Content.scenes_path + "Location/" + context_name + ".tscn")
	if !context_scene:
		return .instance_as(context_name, secondary_contexts)
	var instance = context_scene.instance()
	instance.set("location", self)
	for secondary_context in secondary_contexts:
		instance.set(secondary_context, secondary_contexts[secondary_context])
	return instance
	
func set_name(value):
	name = value
	emit_changed()

func set_location_type(value):
	if typeof(value) == TYPE_STRING:
		location_type = Content.find("LocationType",value)
	else:
		location_type = value

	emit_changed()
func set_position(value):
	position = value
	emit_changed()
func set_level(value):
	level = value
	emit_changed()
func set_starting(value):
	starting = value
	emit_changed()
func set_current(value):
	current = value
	emit_changed()
func set_visited(value):
	visited = value
	emit_changed()
func set_actual_position(value):
	actual_position = value
	emit_changed()
