extends "res://CM/Resources/ActiveRecord.gd"

###WARNING. This file is automatically generated and is not supposed to be edited manually.
###If you need to define custom functions for this resource, use the script in the 'Game/Models' directory instead.
### A single map with locations + connections generated
###
###levels - amount of levels for this map
###
###max_locations - max locations per level
export var name : String setget set_name
export var levels := 5 setget set_levels
export var max_locations := 5 setget set_max_locations

func _to_string():
	return "[Map:{name}]".format({"name" : get("name")})
	

func instance_as(context_name : String, secondary_contexts = {}):
	var context_scene = load(Content.scenes_path + "Map/" + context_name + ".tscn")
	if !context_scene:
		return .instance_as(context_name, secondary_contexts)
	var instance = context_scene.instance()
	instance.set("map", self)
	for secondary_context in secondary_contexts:
		instance.set(secondary_context, secondary_contexts[secondary_context])
	return instance
	
func set_name(value):
	name = value
	emit_changed()
func set_levels(value):
	levels = value
	emit_changed()
func set_max_locations(value):
	max_locations = value
	emit_changed()
