extends "res://CM/Resources/ActiveRecord.gd"

###WARNING. This file is automatically generated and is not supposed to be edited manually.
###If you need to define custom functions for this resource, use the script in the 'Game/Models' directory instead.
### Connection from one location to another. To be created and managed by a map object.
export var name : String setget set_name
export (Resource) var from = Location.new() setget set_from
export (Resource) var to = Location.new() setget set_to

func _to_string():
	return "[MapConnection:{name}]".format({"name" : get("name")})
	

func instance_as(context_name : String, secondary_contexts = {}):
	var context_scene = load(Content.scenes_path + "MapConnection/" + context_name + ".tscn")
	if !context_scene:
		return .instance_as(context_name, secondary_contexts)
	var instance = context_scene.instance()
	instance.set("map_connection", self)
	for secondary_context in secondary_contexts:
		instance.set(secondary_context, secondary_contexts[secondary_context])
	return instance
	
func set_name(value):
	name = value
	emit_changed()
func set_from(value):
	from = value
	emit_changed()
func set_to(value):
	to = value
	emit_changed()
